export const SUPPORTED_COUNTRY_OPTIONS = [
  { value: 'GH', label: 'Ghana' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'US', label: 'United States' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'CA', label: 'Canada' },
  { value: 'KE', label: 'Kenya' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'FR', label: 'France' },
  { value: 'DE', label: 'Germany' },
  { value: 'IT', label: 'Italy' },
  { value: 'ES', label: 'Spain' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'IE', label: 'Ireland' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'SE', label: 'Sweden' },
  { value: 'NO', label: 'Norway' },
  { value: 'DK', label: 'Denmark' },
  { value: 'AE', label: 'United Arab Emirates' },
  { value: 'IN', label: 'India' },
  { value: 'CN', label: 'China' },
  { value: 'JP', label: 'Japan' },
  { value: 'AU', label: 'Australia' },
  { value: 'BR', label: 'Brazil' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'UG', label: 'Uganda' },
] as const;

export const SUPPORTED_COUNTRY_CODES = SUPPORTED_COUNTRY_OPTIONS.map((country) => country.value) as [
  'GH',
  'GB',
  'US',
  'NG',
  'CA',
  'KE',
  'ZA',
  'FR',
  'DE',
  'IT',
  'ES',
  'NL',
  'IE',
  'CH',
  'SE',
  'NO',
  'DK',
  'AE',
  'IN',
  'CN',
  'JP',
  'AU',
  'BR',
  'TZ',
  'UG'
];
